<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>EB2014-102-S</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>11</LastSerialNumber>
            <Stage3Mass>1474.18</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>698.5</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>1</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>189.001</KnownMass>
                    <Density>1049.21</Density>
                    <Material>Polystyrene PS</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>177.8</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>243.61428921195363</CalcMass>
                    <CalcCG>177.8</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>241.3</Len>
                    <FinishCode>0</FinishCode>
                    <SerialNo>0</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>3.175</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>340.194</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass</Name>
                            <KnownCG>336.55</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>336.55</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>1</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                    <BaseDia>101.6</BaseDia>
                    <ShoulderLen>76.2</ShoulderLen>
                    <ShoulderOD>99.06</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>103.58486787025709</KnownMass>
                    <Density>848.979</Density>
                    <Material>Spiral/Glassine</Material>
                    <Name>Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>103.58486787025709</CalcMass>
                    <CalcCG>152.4</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>304.8</Len>
                    <FinishCode>0</FinishCode>
                    <SerialNo>2</SerialNo>
                    <OD>101.6</OD>
                    <ID>99.06</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>99.06</MotorDia>
                    <EngineOverhang>0.5</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>36.8544</KnownMass>
                            <Density>848.979</Density>
                            <Material>Spiral/Glassine</Material>
                            <Name>Tube coupler</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-76.2</Xb>
                            <CalcMass>35.474539243415805</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>152.4</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <OD>99.06</OD>
                            <ID>97.282</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>33.06829298050811</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-76.2</Xb>
                            <CalcMass>33.06829298050811</CalcMass>
                            <CalcCG>2.9591</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>5.9182</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>4</SerialNo>
                            <OD>99.06</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>267.5942419981638</KnownMass>
                    <Density>848.979</Density>
                    <Material>Spiral/Glassine</Material>
                    <Name>Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>267.5942419981638</CalcMass>
                    <CalcCG>393.7</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>787.4</Len>
                    <FinishCode>0</FinishCode>
                    <SerialNo>5</SerialNo>
                    <OD>101.6</OD>
                    <ID>99.06</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>99.06</MotorDia>
                    <EngineOverhang>0.5</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <BodyTube>
                            <KnownMass>74.58110486658558</KnownMass>
                            <Density>848.979</Density>
                            <Material>Spiral/Glassine</Material>
                            <Name>Body tube</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>74.58110486658558</CalcMass>
                            <CalcCG>228.6</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>457.2</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <OD>41.656</OD>
                            <ID>38.608</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>38.608</MotorDia>
                            <EngineOverhang>12.7</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <Ring>
                            <KnownMass>25.11789875029362</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Centering ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>368.3</Xb>
                            <CalcMass>25.11789875029362</CalcMass>
                            <CalcCG>2.7305</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>5.461</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <OD>99.06</OD>
                            <ID>41.656</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>25.11789875029362</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Centering ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>25.11789875029362</CalcMass>
                            <CalcCG>2.7305</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>5.461</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <OD>99.06</OD>
                            <ID>41.656</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Parachute>
                            <KnownMass>87.8835</KnownMass>
                            <Density>0.006685</Density>
                            <Material>Rip stop nylon</Material>
                            <Name>Parachute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>130.175</Xb>
                            <CalcMass>87.88934202854642</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <Dia>1219.2</Dia>
                            <ShroudLineCount>10</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>965.2</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.00102</ShroudLineMassPerMM>
                            <ShroudLineMaterial>1/16 In. braided nylon</ShroudLineMaterial>
                            <DragCoefficient>0.75</DragCoefficient>
                        </Parachute>
                        <MassObject>
                            <KnownMass>198.447</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass</Name>
                            <KnownCG>114.3</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>114.3</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>10</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <FinSet>
                            <KnownMass>130.7960095108126</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Fin set</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>130.7960095108126</CalcMass>
                            <CalcCG>102.96071428571429</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>171.45</RootChord>
                            <TipChord>95.25</TipChord>
                            <SemiSpan>57.15</SemiSpan>
                            <SweepDistance>76.2</SweepDistance>
                            <Thickness>5.9182</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>0.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>