<RockSimDocument>
  <FileVersion>3</FileVersion>
  <DesignInformation>
    <RocketDesign>
      <Name><![CDATA[Madcow Rocketry 4" Patriot]]></Name>
      <CalculateCD>0</CalculateCD>
      <ProCalculateCD>1</ProCalculateCD>
      <ProCalculateCN>1</ProCalculateCN>
      <FixedCd>0.75</FixedCd>
      <FixedCd2>0.8</FixedCd2>
      <FixedCd3>0.81</FixedCd3>
      <FixedCd2Alone>0.95</FixedCd2Alone>
      <FixedCd3Alone>0.95</FixedCd3Alone>
      <StageCount>1</StageCount>
      <Stage3Mass>1474.18</Stage3Mass>
      <Stage2Mass>0.</Stage2Mass>
      <Stage1Mass>0.</Stage1Mass>
      <Stage321CG>0.</Stage321CG>
      <Stage32CG>0.</Stage32CG>
      <Stage3CG>698.5</Stage3CG>
      <Stage2CGAlone>0.</Stage2CGAlone>
      <Stage1CGAlone>0.</Stage1CGAlone>
      <CPCalcFlags>4</CPCalcFlags>
      <LaunchGuideLength>914.4</LaunchGuideLength>
      <UseKnownMass>1</UseKnownMass>
      <DefaultFinish>0</DefaultFinish>
      <FinishMedium>0</FinishMedium>
      <FinishCoatCount>1</FinishCoatCount>
      <GlueType>0</GlueType>
      <CPSimFlags>1</CPSimFlags>
      <LastSerialNumber>15</LastSerialNumber>
      <DisplayFlags>1</DisplayFlags>
      <MetricsFlags>0</MetricsFlags>
      <BarromanXN>0,823.848,0,0</BarromanXN>
      <BarrowmanCNa>0,5.50369,0,0</BarrowmanCNa>
      <RockSimXN>0,922.354,0,0</RockSimXN>
      <RockSimCNa>0,7.26158,0,0</RockSimCNa>
      <RockSimCNa90>0,0,0,0</RockSimCNa90>
      <RockSimXN90>0,0,0,0</RockSimXN90>
      <ViewType>0</ViewType>
      <ViewStageCount>1</ViewStageCount>
      <ViewTypeEdit>0</ViewTypeEdit>
      <ViewStageCountEdit>1</ViewStageCountEdit>
      <ZoomFactor>0.</ZoomFactor>
      <ZoomFactorEdit>0.</ZoomFactorEdit>
      <ScrollPosX>0</ScrollPosX>
      <ScrollPosY>0</ScrollPosY>
      <ScrollPosXEdit>0</ScrollPosXEdit>
      <ScrollPosYEdit>0</ScrollPosYEdit>
      <ThreeDFlags>0</ThreeDFlags>
      <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
      <UseModelSprite>0</UseModelSprite>
      <StaticMarginRef>0</StaticMarginRef>
      <UserRefDiameter>0.</UserRefDiameter>
      <SideMarkerHeight>9.99998</SideMarkerHeight>
      <SideDimensionHeight>9.99998</SideDimensionHeight>
      <BaseMarkerHeight>9.99998</BaseMarkerHeight>
      <BaseDimensionHeight>9.99998</BaseDimensionHeight>
      <Cd3>
        <PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
        <X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
        <A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
        <B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
        <C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
      </PolyData>
    </Cd3>
    <Cd32>
      <PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
      <X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
      <A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
      <B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
      <C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
    </PolyData>
  </Cd32>
  <Cd321>
    <PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
    <X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
    <A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
    <B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
    <C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
  </PolyData>
</Cd321>
<Cb3>
  <PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
  <X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
  <A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
  <B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
  <C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cb3>
<Cb32>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cb32>
<Cb321>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cb321>
<CNa3>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CNa3>
<CNa32>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CNa32>
<CNa321>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CNa321>
<CP3>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CP3>
<CP32>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CP32>
<CP321>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CP321>
<SimulationEventList>
<SimulationEvent>
<PartSerialNo>10</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</SimulationEventList>
<Stage3Parts>
<NoseCone>
<PartMfg>Madcow</PartMfg>
<KnownMass>189.001</KnownMass>
<Density>1049.21</Density>
<Material>Polystyrene PS</Material>
<Name>Nose cone</Name>
<KnownCG>177.8</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>266.354</CalcMass>
<CalcCG>201.722</CalcCG>
<WettedSurface>0.0526977</WettedSurface>
<PaintedSurface>0.0526977</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>PNC101AJ</PartNo>
<PartDesc>Plastic Nosecone w/eyebolt</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(255,0,0)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>1</SerialNo>
<DisplayFlags>1</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(255,0,0)</Color>
<BarrowmanCNa>2.</BarrowmanCNa>
<BarrowmanXN>0.110989</BarrowmanXN>
<RockSimCNa>2.</RockSimCNa>
<RockSimXN>0.110989</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Len>241.3</Len>
<BaseDia>101.6</BaseDia>
<FinishCode>0</FinishCode>
<ShapeCode>1</ShapeCode>
<ConstructionType>1</ConstructionType>
<ShoulderLen>76.2</ShoulderLen>
<WallThickness>3.175</WallThickness>
<ShapeParameter>0.</ShapeParameter>
<ShoulderOD>99.06</ShoulderOD>
<BaseExtensionLen>0.</BaseExtensionLen>
<CoreDia>0.</CoreDia>
<CoreLen>0.</CoreLen>
<AttachedParts>
<MassObject>
<PartMfg>Custom</PartMfg>
<KnownMass>340.194</KnownMass>
<Density>0.</Density>
<Material>Custom</Material>
<Name>Mass</Name>
<KnownCG>336.55</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>336.55</Xb>
<CalcMass>0.</CalcMass>
<CalcCG>0.</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,250)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>11</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(0,0,250)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<TypeCode>0</TypeCode>
<Len>0.</Len>
<AttachedParts>
</AttachedParts>
</MassObject>
</AttachedParts>
</NoseCone>
<BodyTube>
<PartMfg>Madcow</PartMfg>
<KnownMass>0.</KnownMass>
<Density>848.979</Density>
<Material>Spiral/Glassine</Material>
<Name>Body tube</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>103.585</CalcMass>
<CalcCG>152.4</CalcCG>
<WettedSurface>0.0972878</WettedSurface>
<PaintedSurface>0.0972878</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>T101-190</PartNo>
<PartDesc>Airframe</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(255,255,255)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>2</SerialNo>
<DisplayFlags>1</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(0,0,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<OD>101.6</OD>
<ID>99.06</ID>
<Len>304.8</Len>
<FinishCode>0</FinishCode>
<IsMotorMount>0</IsMotorMount>
<MotorDia>0.</MotorDia>
<EngineOverhang>0.5</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>0</IsInsideTube>
<AttachedParts>
<Ring>
<PartMfg>Madcow</PartMfg>
<KnownMass>36.8544</KnownMass>
<Density>848.979</Density>
<Material>Spiral/Glassine</Material>
<Name>Tube coupler</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>-76.2</Xb>
<CalcMass>35.4745</CalcMass>
<CalcCG>76.2</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>C101-600</PartNo>
<PartDesc>Tube Coupler</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,250)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>6</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>rgb(0,0,250)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<OD>99.06</OD>
<ID>97.282</ID>
<Len>152.4</Len>
<FinishCode>0</FinishCode>
<UsageCode>4</UsageCode>
<AutoSize>1</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
<Ring>
<PartMfg>Madcow</PartMfg>
<KnownMass>5.00086</KnownMass>
<Density>724.996</Density>
<Material>Aircraft plywood (Birch)</Material>
<Name>Bulkhead</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>-76.2</Xb>
<CalcMass>33.0683</CalcMass>
<CalcCG>2.9591</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>CB80C</PartNo>
<PartDesc>Coupler Bulkhead</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>7</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<OD>99.06</OD>
<ID>0.</ID>
<Len>5.9182</Len>
<FinishCode>0</FinishCode>
<UsageCode>1</UsageCode>
<AutoSize>1</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
</AttachedParts>
</BodyTube>
<BodyTube>
<PartMfg>Madcow</PartMfg>
<KnownMass>0.</KnownMass>
<Density>848.979</Density>
<Material>Spiral/Glassine</Material>
<Name>Body tube</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>267.594</CalcMass>
<CalcCG>393.7</CalcCG>
<WettedSurface>0.251327</WettedSurface>
<PaintedSurface>0.251327</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>T101-310</PartNo>
<PartDesc>Airframe</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(255,255,255)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>3</SerialNo>
<DisplayFlags>1</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(0,0,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<OD>101.6</OD>
<ID>99.06</ID>
<Len>787.4</Len>
<FinishCode>0</FinishCode>
<IsMotorMount>0</IsMotorMount>
<MotorDia>0.</MotorDia>
<EngineOverhang>0.5</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>0</IsInsideTube>
<AttachedParts>
<BodyTube>
<PartMfg>Madcow</PartMfg>
<KnownMass>0.</KnownMass>
<Density>848.979</Density>
<Material>Spiral/Glassine</Material>
<Name>Body tube</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>74.5811</CalcMass>
<CalcCG>228.6</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>T38-800</PartNo>
<PartDesc>Motor mount tube</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,250)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>5</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>rgb(0,0,250)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<OD>41.656</OD>
<ID>38.608</ID>
<Len>457.2</Len>
<FinishCode>0</FinishCode>
<IsMotorMount>1</IsMotorMount>
<MotorDia>38.</MotorDia>
<EngineOverhang>12.7</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>1</IsInsideTube>
<AttachedParts>
</AttachedParts>
</BodyTube>
<Ring>
<PartMfg>Madcow</PartMfg>
<KnownMass>0.</KnownMass>
<Density>724.996</Density>
<Material>Aircraft plywood (Birch)</Material>
<Name>Centering ring</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>368.3</Xb>
<CalcMass>30.5137</CalcMass>
<CalcCG>2.7305</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>CR10138</PartNo>
<PartDesc>Centering Ring</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,250)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>8</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(0,0,250)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<OD>99.06</OD>
<ID>41.656</ID>
<Len>5.461</Len>
<FinishCode>0</FinishCode>
<UsageCode>0</UsageCode>
<AutoSize>0</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
<Ring>
<PartMfg>Madcow</PartMfg>
<KnownMass>0.</KnownMass>
<Density>724.996</Density>
<Material>Aircraft plywood (Birch)</Material>
<Name>Centering ring</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>30.5137</CalcMass>
<CalcCG>2.7305</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>CR10138</PartNo>
<PartDesc>Centering Ring</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,250)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>9</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>rgb(0,0,250)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<OD>99.06</OD>
<ID>41.656</ID>
<Len>5.461</Len>
<FinishCode>0</FinishCode>
<UsageCode>0</UsageCode>
<AutoSize>0</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
<Parachute>
<PartMfg>Madcow</PartMfg>
<KnownMass>87.8835</KnownMass>
<Density>0.006685</Density>
<Material>Rip stop nylon</Material>
<Name>Parachute</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>130.175</Xb>
<CalcMass>82.8546</CalcMass>
<CalcCG>101.6</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>1</DensityType>
<PartNo>P36</PartNo>
<PartDesc><![CDATA[36" Nylon  10 lines]]></PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>10</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Dia>1219.2</Dia>
<SpillHoleDia>0.</SpillHoleDia>
<SideCount>10</SideCount>
<ShroudLineCount>10</ShroudLineCount>
<Thickness>0.024892</Thickness>
<ShroudLineLen>965.2</ShroudLineLen>
<ChuteCount>1</ChuteCount>
<ShroudLineMassPerMM>0.00102</ShroudLineMassPerMM>
<ShroudLineMaterial>1/16 In. braided nylon</ShroudLineMaterial>
<DragCoefficient>0.75</DragCoefficient>
<AttachedParts>
</AttachedParts>
</Parachute>
<MassObject>
<PartMfg>Custom</PartMfg>
<KnownMass>198.447</KnownMass>
<Density>0.</Density>
<Material>Custom</Material>
<Name>Mass</Name>
<KnownCG>114.3</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>114.3</Xb>
<CalcMass>0.</CalcMass>
<CalcCG>0.</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,250)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>14</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>rgb(0,0,250)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<TypeCode>0</TypeCode>
<Len>0.</Len>
<AttachedParts>
</AttachedParts>
</MassObject>
<FinSet>
<PartMfg>Custom</PartMfg>
<KnownMass>0.</KnownMass>
<Density>724.996</Density>
<Material>Aircraft plywood (Birch)</Material>
<Name>Fin set</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>130.796</CalcMass>
<CalcCG>102.961</CalcCG>
<WettedSurface>0.0152419</WettedSurface>
<PaintedSurface>0.0609676</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,0)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>15</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>rgb(0,0,250)</Color>
<BarrowmanCNa>3.50369</BarrowmanCNa>
<BarrowmanXN>1.23077</BarrowmanXN>
<RockSimCNa>5.26158</RockSimCNa>
<RockSimXN>1.23077</RockSimXN>
<SimpleColorModel>0</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<FinCount>4</FinCount>
<RootChord>171.45</RootChord>
<TipChord>95.25</TipChord>
<SemiSpan>57.15</SemiSpan>
<MidChordLen>68.6858</MidChordLen>
<SweepDistance>76.2</SweepDistance>
<Thickness>5.9182</Thickness>
<ShapeCode>0</ShapeCode>
<FinishCode>0</FinishCode>
<TipShapeCode>0</TipShapeCode>
<TabLength>0.</TabLength>
<TabDepth>0.</TabDepth>
<TabOffset>0.</TabOffset>
<SweepMode>1</SweepMode>
<SweepAngle>0.359992</SweepAngle>
<RockSimXNPerFin>0.</RockSimXNPerFin>
<RockSimRadialXNPerFin>76.6536</RockSimRadialXNPerFin>
<RockSimCNaPerFin>2.63079</RockSimCNaPerFin>
<TaperRatio>0.555556</TaperRatio>
<CantAngle>0.</CantAngle>
<CantPivotPoint>0.</CantPivotPoint>
<AttachedParts>
</AttachedParts>
</FinSet>
</AttachedParts>
</BodyTube>
</Stage3Parts>
<Stage2Parts>
</Stage2Parts>
<Stage1Parts>
</Stage1Parts>
<SideViewDims>
</SideViewDims>
<BaseViewDims>
</BaseViewDims>
<VertViewDims>
</VertViewDims>
</RocketDesign>
</DesignInformation>
<SimulationResultsList>
<SimulationResults>
<MaxAltitude>707.197</MaxAltitude>
<MaxVelocity>168.757</MaxVelocity>
<MaxAcceleration>477.499</MaxAcceleration>
<TimeToApogee>10.5263</TimeToApogee>
<OptimalDelay>8.325</OptimalDelay>
<MultiDelayCount>1</MultiDelayCount>
<VelocityAtDeplyment>44.0411</VelocityAtDeplyment>
<AltitudeAtDeployment>569.613</AltitudeAtDeployment>
<DelayTime>14</DelayTime>
<EjectTime>16.2</EjectTime>
<FinalState>2</FinalState>
<TimeToBurnout>2.20125</TimeToBurnout>
<TimeToLanding>107.794</TimeToLanding>
<TimeToEject>16.2</TimeToEject>
<MinLaunchGuideLen>0.568504</MinLaunchGuideLen>
<MaxVertVelocity>168.667</MaxVertVelocity>
<MaxHorzVelocity>2.84743</MaxHorzVelocity>
<MaxVertAcceleration>477.499</MaxVertAcceleration>
<MaxHorzAcceleration>1.53416</MaxHorzAcceleration>
<MaxRange>195.932</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>914.4</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>759.813</LaunchBarometer>
<LaunchLatitude>0.000000000000000</LaunchLatitude>
<LaunchLongitude>0.000000000000000</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>43.3333</LaunchTemperature>
<LaunchAltitude>0.</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>3</LaunchWindPreset>
<LaunchWindLowSpeed>1.34112</LaunchWindLowSpeed>
<LaunchWindHighSpeed>3.53162</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.01</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
<LaunchCCLow>0.</LaunchCCLow>
<LaunchCCHigh>0.1</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[I211W-14] </SimulationName>
<VelocityAtLaunchGuideEnd>16.8935</VelocityAtLaunchGuideEnd>
<WindStartAltitude>0.</WindStartAltitude>
<TimeToWindShear>0.</TimeToWindShear>
<TimeToFreeFlight>0.10375</TimeToFreeFlight>
<TimeToMaxVelocity>1.82625</TimeToMaxVelocity>
<TimeToMaxAcceleration>16.2013</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>800.</SamplesPerSecond>
<SimulationType>0</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
<ExecutionTime>2.273</ExecutionTime>
<RangeAtLanding>195.932</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>6.36955</VelocityAtLanding>
<XVelcoityAtLanding>1.88156</XVelcoityAtLanding>
<YVelocityAtLanding>-6.0853</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,16.2,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,16.2,0,0</TimeToDeployment>
<DeploymentType>32,32,80,32,32</DeploymentType>
<SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>1.95048</Mass0>
<CG0>0.826141</CG0>
<LaterialMOI0>0.416708</LaterialMOI0>
<RadialMOI0>0.00343962</RadialMOI0>
<GUID>{8b4c8b96-b899-4faa-9a4b-47f40bd1f6c2}</GUID>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>10</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>569.613</DeployedAt_Altitude>
<DeployedAt_Velocity>44.0411</DeployedAt_Velocity>
<DeployedAt_Range>-20.1384</DeployedAt_Range>
<DeployedAt_Time>16.2</DeployedAt_Time>
<DeviceID>128</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>I211W</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Aerotech</EngineMfg>
<EngineOverhang>12.7</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>5</MountSerialNo>
<EjectionDelay>14.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
</SimulationResults>
<SimulationResults>
<MaxAltitude>531.685</MaxAltitude>
<MaxVelocity>142.212</MaxVelocity>
<MaxAcceleration>528.382</MaxAcceleration>
<TimeToApogee>9.42875</TimeToApogee>
<OptimalDelay>7.9275</OptimalDelay>
<MultiDelayCount>1</MultiDelayCount>
<VelocityAtDeplyment>45.2962</VelocityAtDeplyment>
<AltitudeAtDeployment>377.918</AltitudeAtDeployment>
<DelayTime>14</DelayTime>
<EjectTime>15.5</EjectTime>
<FinalState>2</FinalState>
<TimeToBurnout>1.50125</TimeToBurnout>
<TimeToLanding>77.0175</TimeToLanding>
<TimeToEject>15.5</TimeToEject>
<MinLaunchGuideLen>0.705135</MinLaunchGuideLen>
<MaxVertVelocity>142.177</MaxVertVelocity>
<MaxHorzVelocity>2.09711</MaxHorzVelocity>
<MaxVertAcceleration>528.382</MaxVertAcceleration>
<MaxHorzAcceleration>0.868685</MaxHorzAcceleration>
<MaxRange>100.139</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>914.4</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>759.813</LaunchBarometer>
<LaunchLatitude>0.000000000000000</LaunchLatitude>
<LaunchLongitude>0.000000000000000</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>43.3333</LaunchTemperature>
<LaunchAltitude>0.</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>3</LaunchWindPreset>
<LaunchWindLowSpeed>1.34112</LaunchWindLowSpeed>
<LaunchWindHighSpeed>3.53162</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.01</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
<LaunchCCLow>0.</LaunchCCLow>
<LaunchCCHigh>0.1</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[I218R-14] </SimulationName>
<VelocityAtLaunchGuideEnd>15.6874</VelocityAtLaunchGuideEnd>
<WindStartAltitude>0.</WindStartAltitude>
<TimeToWindShear>0.</TimeToWindShear>
<TimeToFreeFlight>0.15125</TimeToFreeFlight>
<TimeToMaxVelocity>1.3625</TimeToMaxVelocity>
<TimeToMaxAcceleration>15.5013</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>800.</SamplesPerSecond>
<SimulationType>0</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
<ExecutionTime>1.689</ExecutionTime>
<RangeAtLanding>100.139</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>6.20614</VelocityAtLanding>
<XVelcoityAtLanding>1.55833</XVelcoityAtLanding>
<YVelocityAtLanding>-6.00731</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,15.5,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,15.5,0,0</TimeToDeployment>
<DeploymentType>32,32,80,32,32</DeploymentType>
<SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>1.84918</Mass0>
<CG0>0.810482</CG0>
<LaterialMOI0>0.413512</LaterialMOI0>
<RadialMOI0>0.00241962</RadialMOI0>
<GUID>{2356992c-0b8f-4ed6-8b4c-8b96b8996faa}</GUID>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>10</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>377.918</DeployedAt_Altitude>
<DeployedAt_Velocity>45.2962</DeployedAt_Velocity>
<DeployedAt_Range>-11.07</DeployedAt_Range>
<DeployedAt_Time>15.5</DeployedAt_Time>
<DeviceID>128</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>I218R</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Aerotech</EngineMfg>
<EngineOverhang>12.7</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>5</MountSerialNo>
<EjectionDelay>14.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
</SimulationResults>
<SimulationResults>
<MaxAltitude>351.287</MaxAltitude>
<MaxVelocity>82.6438</MaxVelocity>
<MaxAcceleration>288.393</MaxAcceleration>
<TimeToApogee>8.61375</TimeToApogee>
<OptimalDelay>6.01375</OptimalDelay>
<MultiDelayCount>1</MultiDelayCount>
<VelocityAtDeplyment>33.4978</VelocityAtDeplyment>
<AltitudeAtDeployment>279.882</AltitudeAtDeployment>
<DelayTime>10</DelayTime>
<EjectTime>12.6</EjectTime>
<FinalState>2</FinalState>
<TimeToBurnout>2.6</TimeToBurnout>
<TimeToLanding>56.5187</TimeToLanding>
<TimeToEject>12.6</TimeToEject>
<MinLaunchGuideLen>1.52584</MinLaunchGuideLen>
<MaxVertVelocity>82.5237</MaxVertVelocity>
<MaxHorzVelocity>2.83657</MaxHorzVelocity>
<MaxVertAcceleration>288.393</MaxVertAcceleration>
<MaxHorzAcceleration>0.707922</MaxHorzAcceleration>
<MaxRange>87.0594</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>914.4</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>759.813</LaunchBarometer>
<LaunchLatitude>0.000000000000000</LaunchLatitude>
<LaunchLongitude>0.000000000000000</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>43.3333</LaunchTemperature>
<LaunchAltitude>0.</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>3</LaunchWindPreset>
<LaunchWindLowSpeed>1.34112</LaunchWindLowSpeed>
<LaunchWindHighSpeed>3.53162</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.01</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
<LaunchCCLow>0.</LaunchCCLow>
<LaunchCCHigh>0.1</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[H123W-10] </SimulationName>
<VelocityAtLaunchGuideEnd>10.632</VelocityAtLaunchGuideEnd>
<WindStartAltitude>0.</WindStartAltitude>
<TimeToWindShear>0.</TimeToWindShear>
<TimeToFreeFlight>0.1675</TimeToFreeFlight>
<TimeToMaxVelocity>2.23375</TimeToMaxVelocity>
<TimeToMaxAcceleration>12.6013</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>800.</SamplesPerSecond>
<SimulationType>0</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
<ExecutionTime>1.42</ExecutionTime>
<RangeAtLanding>87.0594</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>7.64859</VelocityAtLanding>
<XVelcoityAtLanding>2.83659</XVelcoityAtLanding>
<YVelocityAtLanding>-7.10315</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,12.6,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,12.6,0,0</TimeToDeployment>
<DeploymentType>32,32,80,32,32</DeploymentType>
<SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>1.76748</Mass0>
<CG0>0.793203</CG0>
<LaterialMOI0>0.407338</LaterialMOI0>
<RadialMOI0>0.00198854</RadialMOI0>
<GUID>{43e8ab12-423e-4066-9f4e-5717ce65bfac}</GUID>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>10</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>279.882</DeployedAt_Altitude>
<DeployedAt_Velocity>33.4978</DeployedAt_Velocity>
<DeployedAt_Range>-27.2852</DeployedAt_Range>
<DeployedAt_Time>12.6</DeployedAt_Time>
<DeviceID>128</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>H123W</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Aerotech</EngineMfg>
<EngineOverhang>12.7</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>5</MountSerialNo>
<EjectionDelay>10.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
</SimulationResults>
<SimulationResults>
<MaxAltitude>141.298</MaxAltitude>
<MaxVelocity>46.5751</MaxVelocity>
<MaxAcceleration>94.3915</MaxAcceleration>
<TimeToApogee>5.9475</TimeToApogee>
<OptimalDelay>3.90625</OptimalDelay>
<MultiDelayCount>1</MultiDelayCount>
<VelocityAtDeplyment>19.5825</VelocityAtDeplyment>
<AltitudeAtDeployment>120.462</AltitudeAtDeployment>
<DelayTime>6</DelayTime>
<EjectTime>8.04125</EjectTime>
<FinalState>2</FinalState>
<TimeToBurnout>2.04125</TimeToBurnout>
<TimeToLanding>27.92</TimeToLanding>
<TimeToEject>8.04125</TimeToEject>
<MinLaunchGuideLen>2.40414</MinLaunchGuideLen>
<MaxVertVelocity>46.4475</MaxVertVelocity>
<MaxHorzVelocity>3.15681</MaxHorzVelocity>
<MaxVertAcceleration>94.3912</MaxVertAcceleration>
<MaxHorzAcceleration>0.323602</MaxHorzAcceleration>
<MaxRange>45.9609</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>914.4</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>759.813</LaunchBarometer>
<LaunchLatitude>0.000000000000000</LaunchLatitude>
<LaunchLongitude>0.000000000000000</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>43.3333</LaunchTemperature>
<LaunchAltitude>0.</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>3</LaunchWindPreset>
<LaunchWindLowSpeed>1.34112</LaunchWindLowSpeed>
<LaunchWindHighSpeed>3.53162</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.01</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
<LaunchCCLow>0.</LaunchCCLow>
<LaunchCCHigh>0.1</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[G61W-6] </SimulationName>
<VelocityAtLaunchGuideEnd>8.14604</VelocityAtLaunchGuideEnd>
<WindStartAltitude>0.</WindStartAltitude>
<TimeToWindShear>0.</TimeToWindShear>
<TimeToFreeFlight>0.265</TimeToFreeFlight>
<TimeToMaxVelocity>1.63875</TimeToMaxVelocity>
<TimeToMaxAcceleration>8.0425</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>800.</SamplesPerSecond>
<SimulationType>0</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
<ExecutionTime>0.944</ExecutionTime>
<RangeAtLanding>45.9609</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>6.69921</VelocityAtLanding>
<XVelcoityAtLanding>3.15682</XVelcoityAtLanding>
<YVelocityAtLanding>-5.9088</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,8.04125,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,8.04125,0,0</TimeToDeployment>
<DeploymentType>32,32,80,32,32</DeploymentType>
<SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>1.66458</Mass0>
<CG0>0.766484</CG0>
<LaterialMOI0>0.420559</LaterialMOI0>
<RadialMOI0>0.00168318</RadialMOI0>
<GUID>{5be321f9-8daf-48a4-ad7f-66a4ba2dde0a}</GUID>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>10</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>120.462</DeployedAt_Altitude>
<DeployedAt_Velocity>19.5825</DeployedAt_Velocity>
<DeployedAt_Range>-15.0741</DeployedAt_Range>
<DeployedAt_Time>8.04125</DeployedAt_Time>
<DeviceID>128</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>G61W</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Aerotech</EngineMfg>
<EngineOverhang>12.7</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>5</MountSerialNo>
<EjectionDelay>6.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
</SimulationResults>
</SimulationResultsList>
</RockSimDocument>
